apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # URL do servidor ACME do Let's Encrypt para produção
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email para notificações sobre certificados (expiração, problemas, etc)
    email: <MEU@EMAIL.COM> # Substitua pelo seu email
    privateKeySecretRef:
      # Nome do secret que armazenará a chave privada da conta ACME
      name: letsencrypt-prod-account-key
    solvers:
      # Configuração para validação HTTP-01 Challenge
      - http01:
          ingress:
            class: nginx
