apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # URL do servidor ACME do Let's Encrypt para staging (testes)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <MEU@EMAIL.COM> # Substitua pelo seu email
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
